# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: My PhD notes
email: charles.delporte@cern.ch
description: >- # this means to ignore newlines until "baseurl:"
  My personal notes from Quiver
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

# theme: minima
# theme: jekyll-theme-modernist
theme: jekyll-theme-architect

plugins:
  - jekyll-feed
  - quivjek

# exclude:
#   - _posts/**/*.jpg
#   - _posts/**/*.png

#jekyll_dir/_config.yml
# plugins: [quivjek]

#jekyll_dir/_config.yml
# notebook_dir: ~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/Quiver.qvlibrary/Tutorial.qvnotebook/
# notebook_dir: /Users/delporte/Library/Containers/com.happenapps.Quiver/Data/Library/Application Support/Quiver/Quiver.qvlibrary/66071922-A3A0-4C6D-AFE3-07EF86919538.qvnotebook/

notebook_dir: /Users/delporte/Library/Containers/com.happenapps.Quiver/Data/Library/Application Support/Quiver/Quiver.qvlibrary/98AC20E7-86CE-4D9D-B1AF-811DA0A2A72E.qvnotebook/

#notebook_dir: ~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/Quiver.qvlibrary/Tutorial.qvnotebook/3C175FCC-B306-4A71-9FBA-24BD1D9B448C.qvnote/

#Tutorial.qvnotebook

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
